#!/usr/bin/env bash
set -euo pipefail


#######################################################################
# Kolory + funkcje komunikatów + pasek postępu
#######################################################################

WHITE="\e[97m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
CYAN="\e[36m"
RESET="\e[0m"

info()    { echo -e "${BLUE}[INFO]${RESET} $1"; }
ok()      { echo -e "${GREEN}[OK]${RESET} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $1"; }
error()   { echo -e "${RED}[ERROR]${RESET} $1"; }

progress_bar() {
    local total=$1
    local i

    for ((i=0; i<=total; i++)); do
        local percent=$(( i * 100 / total ))
        local filled=$(( percent / 2 ))
        local bar=$(printf "%-${filled}s" "#" | tr ' ' '#')

        printf "\r${CYAN}[%-50s] %3d%%${RESET}" "$bar" "$percent"
        sleep 0.03
    done
    echo ""
}


#######################################################################
# Sprawdzanie systemu — tylko CachyOS
#######################################################################

info "Sprawdzam, czy system to CachyOS..."

if grep -qi "CachyOS" /etc/os-release; then
    ok "Wykryto CachyOS — kontynuuję."
else
    error "Ten skrypt działa WYŁĄCZNIE na CachyOS!"
    exit 1
fi


#######################################################################
# Sprawdzanie połączenia z internetem
#######################################################################

info "Sprawdzam połączenie z internetem..."

if ping -c1 archlinux.org &>/dev/null; then
    ok "Połączenie z internetem działa."
else
    error "Brak połączenia z internetem! Sprawdź sieć i uruchom skrypt ponownie."
    exit 1
fi


#######################################################################
# Banner CachyOS (minimalistyczny)
#######################################################################

arch_logo() {
    echo -e "${CYAN}"

    echo "=================================="
    echo "       CachyOS - KDE Plasma       "
    echo "     Skrypt Instalacyjny 2026     "
    echo "=================================="

    echo ""
    echo -e "${YELLOW}Autor Skryptu: Krzysiek Wierciuch (Hulig1n19)${RESET}"
    echo ""
    echo -e "${RED}Godzina Utworzenia Skryptu: 20:26${RESET}"
    echo ""
    echo -e "${GREEN}Data Utworzenia Skryptu: 02.03.2026${RESET}"
    echo ""
    echo -e "${WHITE}Utworzono Specjalnie Dla: Komputera Stacjonarnego${RESET}"
    echo ""
}

arch_logo
sleep 1


#######################################################################
# 1. Aktualizacja systemu
#######################################################################

info "Aktualizacja systemu..."
progress_bar 20
sudo pacman -Syu --noconfirm
ok "System zaktualizowany."


#######################################################################
# 2. Optymalizacja mirrorów przez reflector (CachyOS)
#######################################################################

info "Konfiguruję mirrory (reflector jest wbudowany w CachyOS)..."

# Sprawdzamy, czy mirrorlist już była generowana przez reflector
if ! grep -q "Generated by Reflector" /etc/pacman.d/mirrorlist 2>/dev/null; then
    info "Generuję zoptymalizowaną listę mirrorów (Polska + Niemcy)..."

    sudo reflector \
        --country Poland,Germany \
        --latest 20 \
        --protocol https \
        --sort rate \
        --save /etc/pacman.d/mirrorlist

    ok "Mirrory zoptymalizowane."
else
    warn "Mirrory już były zoptymalizowane — pomijam."
fi


#######################################################################
# Funkcja naprawy mirrorów (DODANA)
#######################################################################

fix_mirrors() {
    info "Naprawiam mirrory..."

    # Usuwamy CDN77 (najczęstszy winowajca błędów i wolnych pobrań)
    sudo sed -i '/cdn77.cachyos.org/d' /etc/pacman.d/cachyos-mirrorlist || true

    # Regenerujemy szybkie mirrory PL + DE
    sudo reflector \
        --country Poland,Germany \
        --latest 20 \
        --protocol https \
        --sort rate \
        --save /etc/pacman.d/mirrorlist || true

    # Odświeżamy listę pakietów
    sudo pacman -Syy --noconfirm || true

    ok "Mirrory naprawione."
}


#######################################################################
# 3. Instalacja pakietów pacman (bez duplikatów)
#######################################################################

PACMAN_PKGS=(

  # --- System / podstawowe narzędzia ---
  flatpak
  p7zip lrzip lzop zip
  ntfs-3g
  sshfs
  unixodbc

  # --- Motywy, czcionki, ikonki ---
  papirus-icon-theme
  noto-fonts-extra
  ttf-jetbrains-mono
  ttf-fira-code

  # --- Narzędzia systemowe / diagnostyka ---
  gsmartcontrol
  gnome-disk-utility
  sweeper
  kfind
  dolphin-plugins

  # --- Aplikacje użytkowe ---
  okular
  filezilla
  kolourpaint
  gnome-maps
  gnome-calendar
  libreoffice-fresh
  libreoffice-fresh-pl
  thunderbird
  putty

  # --- Multimedia / grafika ---
  obs-studio
  gst-plugins-good
  libgphoto2

  # --- Gry / optymalizacja ---
  steam
  mangohud
  occt
  gamemode
  gamescope
  heroic-games-launcher-bin

  # --- Programowanie / kompilacja ---
  cmake
  ninja

  # --- Sieć / serwery ---
  samba

  # --- Emulatory / Wine ---
  wine
  wine-gecko
  wine-mono
  dosbox

  # --- Sprzęt / sterowniki ---
  lact
  openrgb

  # --- Inne ---
  scrcpy
  kclock
  dunst
)

info "Instalacja pakietów pacman..."

for pkg in "${PACMAN_PKGS[@]}"; do
  if pacman -Qi "$pkg" &>/dev/null; then
    warn "Pominięto — $pkg już jest."
  else
    info "Instaluję: $pkg"

    # próba 1
    if ! sudo pacman -S --noconfirm --needed --disable-download-timeout "$pkg"; then
        warn "Błąd mirrorów — ponawiam instalację $pkg..."

        # próba 2
        sudo pacman -S --noconfirm --needed --disable-download-timeout "$pkg" || {
            error "Nie udało się zainstalować $pkg nawet po ponowieniu!"
            continue
        }
    fi

    ok "$pkg zainstalowany."
  fi
done


#######################################################################
# 4. Flatpak + Flathub
#######################################################################

info "Konfiguruję Flatpak..."
if ! flatpak remote-list | grep -q '^flathub'; then
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  ok "Dodano Flathub."
else
  warn "Flathub już istnieje."
fi


#######################################################################
# 5. Aplikacje Flatpak
#######################################################################

FLATPAK_APPS=(
  com.vysp3r.ProtonPlus
)

info "Instaluję aplikacje Flatpak..."

for app in "${FLATPAK_APPS[@]}"; do
  if ! flatpak list | grep -q "$app"; then
    info "Instaluję: $app"

    ATTEMPT=1
    MAX_ATTEMPTS=3

    while (( ATTEMPT <= MAX_ATTEMPTS )); do
        if flatpak install -y flathub "$app"; then
            ok "$app zainstalowany."
            break
        else
            warn "Błąd podczas instalacji $app — ponawiam próbę..."
            ((ATTEMPT++))
            sleep 1
        fi
    done

    if (( ATTEMPT > MAX_ATTEMPTS )); then
        error "Nie udało się zainstalować $app po $MAX_ATTEMPTS próbach!"
    fi

  else
    warn "Pominięto — $app już jest."
  fi
done


#######################################################################
# 6. Usługi (tylko jeśli nieaktywne)
#######################################################################

info "Sprawdzam usługi..."

if ! systemctl is-active --quiet lactd 2>/dev/null; then
  sudo systemctl enable --now lactd
  ok "lactd uruchomiony."
else
  warn "lactd już działa."
fi


#######################################################################
# 7. Instalacja yay
#######################################################################

info "Sprawdzam yay..."
if ! command -v yay >/dev/null 2>&1; then
  info "Instaluję yay..."
  git clone https://aur.archlinux.org/yay.git /tmp/yay
  cd /tmp/yay
  makepkg -si --noconfirm
  cd -
  ok "yay zainstalowany."
else
  warn "yay już jest."
fi


#######################################################################
# 8. Instalacja AUR (bez duplikatów)
#######################################################################

AUR_PKGS=(
  xone-dkms
)

for pkg in "${AUR_PKGS[@]}"; do
  if ! pacman -Qi "$pkg" >/dev/null 2>&1; then

    ATTEMPT=1
    MAX_ATTEMPTS=4

    while (( ATTEMPT <= MAX_ATTEMPTS )); do
        info "Instaluję z AUR: $pkg (próba $ATTEMPT z $MAX_ATTEMPTS)"

        if yay -S --noconfirm "$pkg"; then
            ok "$pkg zainstalowany z AUR."
            break
        else
            warn "Błąd mirrorów podczas instalacji $pkg — naprawiam mirrory..."
            fix_mirrors
            ((ATTEMPT++))
            sleep 1
        fi
    done

    if (( ATTEMPT > MAX_ATTEMPTS )); then
        error "Nie udało się zainstalować $pkg z AUR po $MAX_ATTEMPTS próbach!"
    fi

  fi
done


#######################################################################
# 9. mkinitcpio — dodanie amdgpu bez duplikatów
#######################################################################

info "Konfiguruję mkinitcpio..."

MKCONF="/etc/mkinitcpio.conf"
sudo touch "$MKCONF"

INITRAMFS_CHANGED=0

if grep -q "^MODULES=" "$MKCONF"; then
    if grep -q "^MODULES=.*amdgpu" "$MKCONF"; then
        warn "amdgpu już jest."
    else
        info "Dodaję amdgpu do MODULES..."
        sudo sed -i \
          -e 's/^MODULES=(\s*\(.*\))/MODULES=(\1 amdgpu)/' \
          -e 's/^MODULES=(\s*/MODULES=(/' \
          "$MKCONF"
        INITRAMFS_CHANGED=1
    fi
else
    info "Dodaję nową linię MODULES=(amdgpu)..."
    LINE=$(grep -n "^# MODULES" "$MKCONF" | cut -d: -f1 || true)
    if [ -n "$LINE" ]; then
        sudo sed -i "$((LINE+1)) i MODULES=(amdgpu)" "$MKCONF"
    else
        printf "\n# MODULES\nMODULES=(amdgpu)\n" | sudo tee -a "$MKCONF" >/dev/null
    fi
    INITRAMFS_CHANGED=1
fi

if [ "$INITRAMFS_CHANGED" = "1" ]; then
    info "Przebudowuję initramfs..."
    sudo mkinitcpio -P
    ok "Initramfs przebudowany."
else
    warn "Initramfs bez zmian."
fi


#######################################################################
# 10. systemd-boot — ustawienie timeout 0 (CachyOS)
#######################################################################

info "Ustawiam timeout 0 w systemd-boot (CachyOS)..."

LOADER_CONF="/boot/loader/loader.conf"

# Upewniamy się, że katalog istnieje (na wszelki wypadek)
if sudo test -d "/boot/loader"; then
    if sudo test -f "$LOADER_CONF"; then
        info "Plik loader.conf istnieje — modyfikuję timeout..."

        # Jeśli jest linia z timeout, podmień ją na timeout 0
        sudo sed -i \
            -e 's/^[[:space:]]*timeout[[:space:]]*=[[:space:]]*[0-9]\+/timeout 0/' \
            -e 's/^[[:space:]]*timeout[[:space:]]\+[0-9]\+/timeout 0/' \
            "$LOADER_CONF"

        # Jeśli po sed dalej nie ma timeoutu, dopisz na końcu
        if ! sudo grep -q '^[[:space:]]*timeout[[:space:]]' "$LOADER_CONF"; then
            echo "timeout 0" | sudo tee -a "$LOADER_CONF" >/dev/null
        fi

        ok "Timeout w loader.conf ustawiony na 0."
    else
        warn "Plik loader.conf nie istnieje — tworzę z timeout 0."
        printf 'timeout 0\n' | sudo tee "$LOADER_CONF" >/dev/null
        ok "Utworzono /boot/loader/loader.conf z timeout 0."
    fi
else
    warn "Katalog /boot/loader nie istnieje lub brak dostępu — pomijam konfigurację systemd-boot."
fi


#######################################################################
# 11. Gamemode — konfiguracja
#######################################################################

info "Konfiguruję gamemode..."

GAMEMODE_CFG="/etc/gamemode.ini"

sudo touch "$GAMEMODE_CFG"
sudo sed -i '1{/^[[:space:]]*$/d}' "$GAMEMODE_CFG"

HAS_GENERAL=$(grep -Fq "[general]" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_RENICE=$(grep -Fq "renice=10" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_CPU=$(grep -Fq "[cpu]" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_GOV=$(grep -Fq "governor=performance" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_GPU=$(grep -Fq "[gpu]" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_GPU_OPT=$(grep -Fq "apply_gpu_optimisations=accept-responsibility" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_GPU_DEV=$(grep -Fq "gpu_device=0" "$GAMEMODE_CFG" && echo yes || echo no)

if [ "$HAS_GENERAL" = yes ] &&
   [ "$HAS_RENICE" = yes ] &&
   [ "$HAS_CPU" = yes ] &&
   [ "$HAS_GOV" = yes ] &&
   [ "$HAS_GPU" = yes ] &&
   [ "$HAS_GPU_OPT" = yes ] &&
   [ "$HAS_GPU_DEV" = yes ]; then

    warn "Konfiguracja gamemode już istnieje."

else
    info "Uzupełniam konfigurację gamemode..."

    if [ "$HAS_GENERAL" = no ]; then
        printf "[general]\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_RENICE" = no ]; then
        printf "renice=10\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi

    if [ "$HAS_CPU" = no ]; then
        printf "\n[cpu]\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_GOV" = no ]; then
        printf "governor=performance\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi

    if [ "$HAS_GPU" = no ]; then
        printf "\n[gpu]\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_GPU_OPT" = no ]; then
        printf "apply_gpu_optimisations=accept-responsibility\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_GPU_DEV" = no ]; then
        printf "gpu_device=0\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi

    ok "Gamemode skonfigurowany."
fi


#######################################################################
# 12. Czyszczenie cache
#######################################################################

info "Czyszczę cache pacmana, yay i flatpaka..."

# Pacman — usuwa stare pakiety z cache
sudo pacman -Sc --noconfirm >/dev/null 2>&1 || true

# Yay — usuwa cache AUR
yay -Sc --noconfirm >/dev/null 2>&1 || true

# Flatpak — usuwa nieużywane runtime’y i zależności
flatpak uninstall --unused -y >/dev/null 2>&1 || true

# Flatpak — usuwa dane po aplikacjach, które już nie istnieją
flatpak remove --unused -y >/dev/null 2>&1 || true

# Flatpak — naprawa i czyszczenie repozytoriów (bezpieczne)
flatpak repair --user -y >/dev/null 2>&1 || true
flatpak repair --system -y >/dev/null 2>&1 || true

ok "Cache pacmana, yay i flatpaka wyczyszczony."


#######################################################################
# 13. Finalna aktualizacja
#######################################################################

info "Finalna aktualizacja systemu..."
sudo pacman -Syu --noconfirm
ok "System gotowy."

echo -e "${GREEN}=== Operacja zakończona sukcesem ===${RESET}"
echo ""
ok "Instalacja zakończona — możesz zrestartować system, kiedy będziesz chciał."
echo ""
