#!/usr/bin/env bash
set -euo pipefail

#######################################################################
# Kolory + funkcje komunikatów + pasek postępu
#######################################################################

WHITE="\e[97m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
CYAN="\e[36m"
RESET="\e[0m"

info()    { echo -e "${BLUE}[INFO]${RESET} $1"; }
ok()      { echo -e "${GREEN}[OK]${RESET} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $1"; }
error()   { echo -e "${RED}[ERROR]${RESET} $1"; }

progress_bar() {
    local duration=$1
    local i=0
    local bar=""
    while [ $i -le $duration ]; do
        bar=$(printf "%-${i}s" "#" | tr ' ' '#')
        printf "\r${CYAN}[%s%-${duration}s]${RESET}" "$bar" ""
        sleep 0.05
        i=$((i+1))
    done
    echo ""
}

#######################################################################
# Banner ARCH LINUX (minimalistyczny)
#######################################################################

arch_logo() {
    echo -e "${CYAN}"

    echo "=================================="
    echo "     ARCH LINUX - KDE Plasma      "
    echo "     Skrypt Instalacyjny 2026     "
    echo "           18.04.2026             "
    echo "=================================="

    echo ""
    echo -e "${YELLOW}Autor Skryptu: Krzysiek Wierciuch (Hulig1n19)${RESET}"
    echo ""
    echo -e "${RED}Godzina Utworzenia Skryptu: 18:12${RESET}"
    echo ""
    echo -e "${GREEN}Data Utworzenia Skryptu: 18.04.2026${RESET}"
    echo ""
    echo -e "${WHITE}Utworzono Specjalnie Dla: HP Pavilion g6${RESET}"
    echo ""
}

arch_logo
sleep 1

#######################################################################
# 1. Aktualizacja systemu
#######################################################################

info "Aktualizacja systemu..."
progress_bar 20
sudo pacman -Syu --noconfirm
ok "System zaktualizowany."


#######################################################################
# 2. Optymalizacja mirrorów przez reflector
#######################################################################

info "Sprawdzam reflector..."

# Instalacja tylko jeśli brak
if ! pacman -Qi reflector >/dev/null 2>&1; then
    info "Instaluję reflector..."
    sudo pacman -S --noconfirm reflector
    ok "reflector zainstalowany."
else
    warn "reflector już jest — pomijam instalację."
fi

# Sprawdzamy, czy mirrorlist już był generowany przez reflector
if ! grep -q "Generated by Reflector" /etc/pacman.d/mirrorlist 2>/dev/null; then
    info "Optymalizuję mirrory (Polska + Niemcy)..."
    sudo reflector --country Poland,Germany --age 12 --protocol https --sort rate \
        --save /etc/pacman.d/mirrorlist
    ok "Mirrory zoptymalizowane."
else
    warn "Mirrory już były zoptymalizowane — pomijam."
fi

#######################################################################
# 3. Instalacja Plasma Desktop + SDDM (bez duplikatów)
#######################################################################

info "Instaluję Plasma Desktop i komponenty KDE..."

PLASMA_PKGS=(
  plasma-desktop
  kde-gtk-config
  konsole
  dolphin
  kate
  nano
  kscreen
  sddm
  sddm-kcm
)

for pkg in "${PLASMA_PKGS[@]}"; do
  if ! pacman -Qi "$pkg" >/dev/null 2>&1; then
    info "Instaluję: $pkg"
    sudo pacman -S --noconfirm "$pkg"
  else
    warn "Pominięto — $pkg już jest."
  fi
done

ok "Plasma Desktop i komponenty KDE zainstalowane."


#######################################################################
# 4. Włączenie menedżera logowania SDDM
#######################################################################

info "Włączam SDDM..."

if ! systemctl is-enabled --quiet sddm 2>/dev/null; then
    sudo systemctl enable sddm
    ok "SDDM włączony."
else
    warn "SDDM już jest włączony."
fi


#######################################################################
# 5. Instalacja pakietów pacman (bez duplikatów)
#######################################################################

PACMAN_PKGS=(
  # Podstawowe narzędzia systemowe
  git base-devel less wget flatpak power-profiles-daemon pacman-contrib

  # Przeglądarka i język
  firefox firefox-i18n-pl

  # KDE Plasma + dodatki
  plasma-nm plasma-pa bluedevil plasma-workspace-wallpapers plasma-browser-integration
  kdeplasma-addons kdeconnect dolphin-plugins kfind breeze-gtk

  # Archiwa i kompresja
  ark p7zip unrar unzip lrzip lzop zip

  # Ikony, kursory, czcionki
  papirus-icon-theme capitaine-cursors noto-fonts-cjk noto-fonts-extra cantarell-fonts
  ttf-jetbrains-mono ttf-fira-code

  # Multimedia i grafika
  gwenview kdegraphics-thumbnailers ffmpegthumbs kolourpaint spectacle vlc vlc-plugins-all

  # Narzędzia systemowe i diagnostyczne
  gsmartcontrol gnome-disk-utility ntfs-3g exfatprogs dosfstools btrfs-progs xfsprogs f2fs-tools
  clinfo kwallet-pam kwalletmanager sweeper btop

  # Programy użytkowe
  elisa putty okular filezilla libreoffice-fresh libreoffice-fresh-pl gnome-maps gnome-calendar
  kcalc scrcpy

  # Programowanie i dev
  cmake ninja vim

  # Vulkan / Mesa / sterowniki
  vulkan-intel lib32-mesa lib32-vulkan-intel

  # Emulacja i gry
  wine wine-gecko wine-mono dosbox gamemode gamescope lutris mangohud

  # Sieć i protokoły
  sshfs samba sane unixodbc libgphoto2

  # Inne
  occt dunst
)

info "Instalacja pakietów pacman..."
for pkg in "${PACMAN_PKGS[@]}"; do
  if ! pacman -Qi "$pkg" >/dev/null 2>&1; then
    info "Instaluję: $pkg"
    sudo pacman -S --noconfirm "$pkg"
  else
    warn "Pominięto — $pkg już jest."
  fi
done
ok "Pakiety pacman zainstalowane."


#######################################################################
# 6. Flatpak + Flathub
#######################################################################

info "Konfiguruję Flatpak..."
if ! flatpak remote-list | grep -q '^flathub'; then
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  ok "Dodano Flathub."
else
  warn "Flathub już istnieje."
fi


#######################################################################
# 7. Aplikacje Flatpak
#######################################################################

FLATPAK_APPS=(
  com.vysp3r.ProtonPlus
)

info "Instaluję aplikacje Flatpak..."

for app in "${FLATPAK_APPS[@]}"; do
  if ! flatpak list | grep -q "$app"; then
    info "Instaluję: $app"
    flatpak install -y flathub "$app"
    ok "$app zainstalowany."
  else
    warn "Pominięto — $app już jest."
  fi
done

ok "Aplikacje Flatpak zainstalowane."


#######################################################################
# 8. Usługi (tylko jeśli nieaktywne)
#######################################################################

info "Sprawdzam usługi..."

if ! systemctl is-active --quiet power-profiles-daemon 2>/dev/null; then
  sudo systemctl enable --now power-profiles-daemon
  ok "power-profiles-daemon uruchomiony."
else
  warn "power-profiles-daemon już działa."
fi


#######################################################################
# 9. Instalacja yay
#######################################################################

info "Sprawdzam yay..."
if ! command -v yay >/dev/null 2>&1; then
  info "Instaluję yay..."
  git clone https://aur.archlinux.org/yay.git /tmp/yay
  cd /tmp/yay
  makepkg -si --noconfirm
  cd -
  ok "yay zainstalowany."
else
  warn "yay już jest."
fi


#######################################################################
# 10. Instalacja AUR (bez duplikatów)
#######################################################################

AUR_PKGS=(
  xone-dkms
)

for pkg in "${AUR_PKGS[@]}"; do
  if ! pacman -Qi "$pkg" >/dev/null 2>&1; then
    yay -S --noconfirm "$pkg"
  fi
done


#######################################################################
# 11. SDDM — dodanie bloku tylko jeśli go nie ma
#######################################################################

info "Konfiguruję SDDM..."

SDDM_FILE="/etc/sddm.conf"
SDDM_BLOCK=$'[General]\nInputMethod=qtvirtualkeyboard\n\n[Theme]\nCurrent=breeze'

sudo touch "$SDDM_FILE"

if grep -Fq "[General]" "$SDDM_FILE" &&
   grep -Fq "InputMethod=qtvirtualkeyboard" "$SDDM_FILE" &&
   grep -Fq "[Theme]" "$SDDM_FILE" &&
   grep -Fq "Current=breeze" "$SDDM_FILE"; then
    warn "Blok SDDM już istnieje."
else
    info "Dodaję blok SDDM..."
    sudo sed -i ':a;/^\s*$/{$d;N;ba}' "$SDDM_FILE"
    printf "%s\n" "$SDDM_BLOCK" | sudo tee -a "$SDDM_FILE" >/dev/null
    ok "Blok SDDM dodany."
fi


#######################################################################
# 12. mkinitcpio — dodanie i915 bez duplikatów
#######################################################################

info "Konfiguruję mkinitcpio..."

MKCONF="/etc/mkinitcpio.conf"
sudo touch "$MKCONF"

INITRAMFS_CHANGED=0

if grep -q "^MODULES=" "$MKCONF"; then
    if grep -q "^MODULES=.*i915" "$MKCONF"; then
        warn "i915 już jest."
    else
        info "Dodaję i915 do MODULES..."
        sudo sed -i \
          -e 's/^MODULES=(\s*\(.*\))/MODULES=(\1 i915)/' \
          -e 's/^MODULES=(\s*/MODULES=(/' \
          "$MKCONF"
        INITRAMFS_CHANGED=1
    fi
else
    info "Dodaję nową linię MODULES=(i915)..."
    LINE=$(grep -n "^# MODULES" "$MKCONF" | cut -d: -f1 || true)
    if [ -n "$LINE" ]; then
        sudo sed -i "$((LINE+1)) i MODULES=(i915)" "$MKCONF"
    else
        printf "\n# MODULES\nMODULES=(i915)\n" | sudo tee -a "$MKCONF" >/dev/null
    fi
    INITRAMFS_CHANGED=1
fi

if [ "$INITRAMFS_CHANGED" = "1" ]; then
    info "Przebudowuję initramfs..."
    sudo mkinitcpio -P
    ok "Initramfs przebudowany."
else
    warn "Initramfs bez zmian."
fi


#######################################################################
# 13. systemd-boot — ustawienie timeout 0
#######################################################################

info "Ustawiam timeout 0 w systemd-boot..."

if [ -f /boot/loader/loader.conf ]; then
    sudo sed -i \
        -e 's/^[[:space:]]*timeout[[:space:]]*=[[:space:]]*[0-9]\+/timeout 0/' \
        -e 's/^[[:space:]]*timeout[[:space:]]\+[0-9]\+/timeout 0/' \
        /boot/loader/loader.conf
    ok "Timeout ustawiony."
else
    warn "Plik loader.conf nie istnieje — pomijam."
fi


#######################################################################
# 14. Gamemode — konfiguracja (Optymalizacja pod Intel)
#######################################################################

info "Konfiguruję gamemode..."

GAMEMODE_CFG="/etc/gamemode.ini"

sudo touch "$GAMEMODE_CFG"
sudo sed -i '1{/^[[:space:]]*$/d}' "$GAMEMODE_CFG"

HAS_GENERAL=$(grep -Fq "[general]" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_RENICE=$(grep -Fq "renice=10" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_CPU=$(grep -Fq "[cpu]" "$GAMEMODE_CFG" && echo yes || echo no)
HAS_GOV=$(grep -Fq "governor=performance" "$GAMEMODE_CFG" && echo yes || echo no)

if [ "$HAS_GENERAL" = yes ] &&
   [ "$HAS_RENICE" = yes ] &&
   [ "$HAS_CPU" = yes ] &&
   [ "$HAS_GOV" = yes ]; then

    warn "Konfiguracja gamemode już istnieje."

else
    info "Uzupełniam konfigurację gamemode..."

    if [ "$HAS_GENERAL" = no ]; then
        printf "[general]\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_RENICE" = no ]; then
        printf "renice=10\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi

    if [ "$HAS_CPU" = no ]; then
        printf "\n[cpu]\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi
    if [ "$HAS_GOV" = no ]; then
        printf "governor=performance\n" | sudo tee -a "$GAMEMODE_CFG" >/dev/null
    fi

    ok "Gamemode skonfigurowany pod procesor."
fi


#######################################################################
# 15. Czyszczenie cache
#######################################################################

info "Czyszczę cache pacmana, yay i flatpaka..."

# Pacman — usuwa stare pakiety z cache
sudo pacman -Sc --noconfirm >/dev/null 2>&1 || true

# Yay — usuwa cache AUR
yay -Sc --noconfirm >/dev/null 2>&1 || true

# Flatpak — usuwa nieużywane runtime’y i zależności
flatpak uninstall --unused -y >/dev/null 2>&1 || true

# Flatpak — usuwa dane po aplikacjach, które już nie istnieją
flatpak remove --unused -y >/dev/null 2>&1 || true

# Flatpak — naprawa i czyszczenie repozytoriów (bezpieczne)
flatpak repair --user -y >/dev/null 2>&1 || true
flatpak repair --system -y >/dev/null 2>&1 || true

ok "Cache pacmana, yay i flatpaka wyczyszczony."


#######################################################################
# 16. Finalna aktualizacja
#######################################################################

info "Finalna aktualizacja systemu..."
sudo pacman -Syu --noconfirm
ok "System gotowy."

echo -e "${GREEN}=== Operacja zakończona sukcesem ===${RESET}"

echo ""
info "Restart systemu nastąpi za 10 sekund."
echo ""

for i in {10..1}; do
    echo "Restart za $i..."
    sleep 1
done

info "Restartuję system..."
sudo systemctl reboot
